export const cars = [
  {
    id: 0,
    title: "Luxury Cruiser",
    category: "Sedan",
    fuel_capacity: 70,
    drive: "Manual",
    sitting: 2,
    per_day_price: "80.00",
    image: "/images/cars/1.png",
    favourite: true,
    original_price: "100.00",
  },
  {
    id: 1,
    title: "Exquisite Speedster",
    category: "Sport",
    fuel_capacity: 90,
    drive: "Manual",
    sitting: 4,
    per_day_price: "85.00",
    image: "/images/cars/2.png",
    favourite: false,
  },
  {
    id: 2,
    title: "Premium SUV",
    category: "Suv",
    fuel_capacity: 80,
    drive: "Manual",
    sitting: 6,
    per_day_price: "78.00",
    image: "/images/cars/3.png",
    favourite: true,
    original_price: "98.00",
  },
  {
    id: 3,
    title: "Elegant Hatchback",
    category: "HatchBack",
    fuel_capacity: 70,
    drive: "Manual",
    sitting: 4,
    per_day_price: "74.00",
    image: "/images/cars/4.png",
    favourite: true,
  },
  {
    id: 4,
    title: "Sophisticated Swedan",
    category: "Swedan",
    fuel_capacity: 80,
    drive: "Manual",
    sitting: 2,
    per_day_price: "82.00",
    image: "/images/cars/5.png",
    favourite: false,
    original_price: "90.00",
  },
  {
    id: 5,
    title: "Luxury Cruiser",
    category: "Sedan",
    fuel_capacity: 90,
    drive: "Manual",
    sitting: 6,
    per_day_price: "76.00",
    image: "/images/cars/6.png",
    favourite: true,
  },
  {
    id: 6,
    title: "Exquisite Speedster",
    category: "Sport",
    fuel_capacity: 70,
    drive: "Manual",
    sitting: 4,
    per_day_price: "79.00",
    image: "/images/cars/33.png",
    favourite: false,
    original_price: "85.00",
  },
  {
    id: 7,
    title: "Premium SUV",
    category: "Suv",
    fuel_capacity: 80,
    drive: "Manual",
    sitting: 2,
    per_day_price: "88.00",
    image: "/images/cars/1.png",
    favourite: false,
  },
  {
    id: 8,
    title: "Elegant Hatchback",
    category: "HatchBack",
    fuel_capacity: 70,
    drive: "Manual",
    sitting: 6,
    per_day_price: "77.00",
    image: "/images/cars/2.png",
    favourite: true,
    original_price: "87.00",
  },
  {
    id: 9,
    title: "Sophisticated Swedan",
    category: "Swedan",
    fuel_capacity: 90,
    drive: "Manual",
    sitting: 4,
    per_day_price: "81.00",
    image: "/images/cars/3.png",
    favourite: false,
  },
  {
    id: 10,
    title: "Luxury Cruiser",
    category: "Sedan",
    fuel_capacity: 80,
    drive: "Manual",
    sitting: 2,
    per_day_price: "86.00",
    image: "/images/cars/4.png",
    favourite: true,
  },
  {
    id: 11,
    title: "Exquisite Speedster",
    category: "Sport",
    fuel_capacity: 70,
    drive: "Manual",
    sitting: 4,
    per_day_price: "75.00",
    image: "/images/cars/5.png",
    favourite: false,
  },
  {
    id: 12,
    title: "Premium SUV",
    category: "Suv",
    fuel_capacity: 90,
    drive: "Manual",
    sitting: 6,
    per_day_price: "83.00",
    image: "/images/cars/6.png",
    favourite: false,
  },
  {
    id: 13,
    title: "Elegant Hatchback",
    category: "HatchBack",
    fuel_capacity: 80,
    drive: "Manual",
    sitting: 2,
    per_day_price: "87.00",
    image: "/images/cars/33.png",
    favourite: true,
  },
  {
    id: 14,
    title: "Sophisticated Swedan",
    category: "Swedan",
    fuel_capacity: 70,
    drive: "Manual",
    sitting: 4,
    per_day_price: "72.00",
    image: "/images/cars/1.png",
    favourite: false,
  },
  {
    id: 15,
    title: "Luxury Cruiser",
    category: "Sedan",
    fuel_capacity: 80,
    drive: "Manual",
    sitting: 6,
    per_day_price: "84.00",
    image: "/images/cars/2.png",
    favourite: false,
  },
  {
    id: 16,
    title: "Exquisite Speedster",
    category: "Sport",
    fuel_capacity: 90,
    drive: "Manual",
    sitting: 2,
    per_day_price: "79.00",
    image: "/images/cars/3.png",
    favourite: true,
  },
  {
    id: 17,
    title: "Premium SUV",
    category: "Suv",
    fuel_capacity: 70,
    drive: "Manual",
    sitting: 4,
    per_day_price: "73.00",
    image: "/images/cars/4.png",
    favourite: false,
  },
  {
    id: 18,
    title: "Elegant Hatchback",
    category: "HatchBack",
    fuel_capacity: 80,
    drive: "Manual",
    sitting: 6,
    per_day_price: "88.00",
    image: "/images/cars/5.png",
    favourite: true,
  },
  {
    id: 19,
    title: "Sophisticated Swedan",
    category: "Swedan",
    fuel_capacity: 70,
    drive: "Manual",
    sitting: 2,
    per_day_price: "75.00",
    image: "/images/cars/6.png",
    favourite: true,
  },
  {
    id: 20,
    title: "Luxury Cruiser",
    category: "Sedan",
    fuel_capacity: 90,
    drive: "Manual",
    sitting: 4,
    per_day_price: "82.00",
    image: "/images/cars/33.png",
    favourite: false,
  },
  {
    id: 21,
    title: "Exquisite Speedster",
    category: "Sport",
    fuel_capacity: 80,
    drive: "Manual",
    sitting: 6,
    per_day_price: "76.00",
    image: "/images/cars/1.png",
    favourite: true,
  },
  {
    id: 22,
    title: "Premium SUV",
    category: "Suv",
    fuel_capacity: 70,
    drive: "Manual",
    sitting: 2,
    per_day_price: "84.00",
    image: "/images/cars/2.png",
    favourite: false,
  },
  {
    id: 23,
    title: "Elegant Hatchback",
    category: "HatchBack",
    fuel_capacity: 90,
    drive: "Manual",
    sitting: 4,
    per_day_price: "77.00",
    image: "/images/cars/3.png",
    favourite: false,
  },
  {
    id: 24,
    title: "Sophisticated Swedan",
    category: "Swedan",
    fuel_capacity: 80,
    drive: "Manual",
    sitting: 6,
    per_day_price: "81.00",
    image: "/images/cars/4.png",
    favourite: true,
  },
];

console.log(cars);
